version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: betabank
      POSTGRES_PASSWORD: betabank
      POSTGRES_DB: betabank
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    environment:
      DATABASE_URL: postgresql://betabank:betabank@db:5432/betabank
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}
    depends_on:
      - backend

volumes:
  postgres_data: 