"""add months to transaction batch

Revision ID: 7b85a0ea0447
Revises: b4418e92852e
Create Date: 2025-05-13 16:54:47.238899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b85a0ea0447'
down_revision: Union[str, None] = 'b4418e92852e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_batches', sa.Column('months', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_batches', 'months')
    # ### end Alembic commands ###
